#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cronie
Version  : 1.6.1
Release  : 27
URL      : https://github.com/cronie-crond/cronie/archive/cronie-1.6.1/cronie-1.6.1.tar.gz
Source0  : https://github.com/cronie-crond/cronie/archive/cronie-1.6.1/cronie-1.6.1.tar.gz
Source1  : cronie.service
Summary  : Cron daemon for executing programs at set times
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ ISC LGPL-2.1 MIT
Requires: cronie-bin = %{version}-%{release}
Requires: cronie-license = %{version}-%{release}
Requires: cronie-man = %{version}-%{release}
Requires: cronie-services = %{version}-%{release}
Requires: cronie-setuid = %{version}-%{release}
Patch1: 0001-Don-t-complain-about-missing-etc-cron.d.patch

%description
Cronie contains the standard UNIX daemon crond that runs specified programs at
scheduled times and related tools. It is a fork of the original vixie-cron and
has security and configuration enhancements like the ability to use pam and
SELinux.

%package bin
Summary: bin components for the cronie package.
Group: Binaries
Requires: cronie-setuid = %{version}-%{release}
Requires: cronie-license = %{version}-%{release}
Requires: cronie-services = %{version}-%{release}

%description bin
bin components for the cronie package.


%package license
Summary: license components for the cronie package.
Group: Default

%description license
license components for the cronie package.


%package man
Summary: man components for the cronie package.
Group: Default

%description man
man components for the cronie package.


%package services
Summary: services components for the cronie package.
Group: Systemd services

%description services
services components for the cronie package.


%package setuid
Summary: setuid components for the cronie package.
Group: Default

%description setuid
setuid components for the cronie package.


%prep
%setup -q -n cronie-cronie-1.6.1
cd %{_builddir}/cronie-cronie-1.6.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1650896136
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1650896136
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cronie
cp %{_builddir}/cronie-cronie-1.6.1/COPYING %{buildroot}/usr/share/package-licenses/cronie/6261e3b944ea705753eeb12c7e6fb0ef3ba42bee
cp %{_builddir}/cronie-cronie-1.6.1/COPYING.anacron %{buildroot}/usr/share/package-licenses/cronie/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/cronie-cronie-1.6.1/COPYING.obstack %{buildroot}/usr/share/package-licenses/cronie/9a1929f4700d2407c70b507b3b2aaf6226a9543c
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/cronie.service

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/anacron
/usr/bin/crond
/usr/bin/cronnext

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cronie/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/cronie/6261e3b944ea705753eeb12c7e6fb0ef3ba42bee
/usr/share/package-licenses/cronie/9a1929f4700d2407c70b507b3b2aaf6226a9543c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cronnext.1
/usr/share/man/man1/crontab.1
/usr/share/man/man5/anacrontab.5
/usr/share/man/man5/crontab.5
/usr/share/man/man8/anacron.8
/usr/share/man/man8/cron.8
/usr/share/man/man8/crond.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/cronie.service

%files setuid
%defattr(-,root,root,-)
%attr(4755,root,cron) /usr/bin/crontab
